spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/sell?useUnicode=true&characterEncoding=utf8&useSSL=true&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: 123456

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null

  redis:
    database: 0
    host: 192.168.2.213
    port: 6379

mybatis:
  mapper-locations: classpath:mapper/**/*.xml

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true


server:
  servlet:
    context-path: /sell
  port: 8080




